### ISSUE TITLE
Encrypt text | ENC-01

### ISSUE THREAD

**Issue by MarcoRossignoli** [tomchavakis/encrypto#1]
Could be very useful allow to encrypt text, for instance to send through email/chats, something like:
```
dotnet-encrypto.exe encrypt -t "textToEncrypt"
dotnet-encrypto.exe encrypt --text "textToEncrypt"
```
after input password print codebase64 text to copy/paste.

**Comment by tomchavakis** [comment]
Hi Marco,

Thank you very much for this nice idea. I will add it asap.

**Comment by MarcoRossignoli** [comment]
Maybe to simplify copy from "console" we could have a non mandatory parameter like -c --charsPerRow similar to cert request https://en.wikipedia.org/wiki/Certificate_signing_request#Example to avoid text wrapped.

**Comment by tomchavakis** [comment]
Hi Marco,

I have uploaded to the master branch the update with this feature.
You can use the nuget update tool using the following command:

`dotnet tool update dotnet-encrypto -g `

in case that you have already install the tool or just install it.

You can find more at the following link:

https://www.nuget.org/packages/dotnet-encrypto/1.0.4

Thank's again for this nice idea!!!

**Comment by MarcoRossignoli** [comment]
Thank's!You could update also https://github.com/tomchavakis/encrypto#usage opstions with new switch!

**Comment by tomchavakis** [comment]
Thank's!! readme updated
