### ISSUE TITLE
Print * instead of real text when input password

### ISSUE THREAD

**Issue by MarcoRossignoli** [tomchavakis/encrypto#3]
When we input "Password" dotnet-encrypto print "real text".
This isn's secure because someone could steal password looking at monitor.
Could be great to have something like:
```
Encryption Started...
Password:
*******
.....rest of output
```

**Comment by tomchavakis** [comment]
I will fix it asap. Does the text mode working fine ?

**Comment by tomchavakis** [comment]
You are right, I will pass that fix.
I have also created a develop branch, in case that you want to collaborate to the project.
I am also thinking to add other encryption algorithms or encoding decoding flags. 
What do you think?

**Comment by MarcoRossignoli** [comment]
> I have also created a develop branch

You could fix new branch every "release"(nuget) to maintain versions and to port future fix(if not breaking chance) on old versions https://docs.microsoft.com/en-us/azure/devops/repos/git/git-branching-guidance?view=vsts
Similar to corefx/coreclr repo https://github.com/dotnet/corefx/branches
If contributors wants to collaborate they could fork and propose PRs directly on master and you'll decide if merge or not.

> I am also thinking to add other encryption algorithms 

I think you could add a switch for algorithm name ie. `-encryptionAlgorithm AES256` could be difficult for asymmetric algorithm(private/public key file) and maybe you'll need to "impose" key length.

> or encoding decoding flags.

It's not clear to me what you mean...for text is console...for file are bytes...

FYI https://docs.microsoft.com/en-us/dotnet/standard/security/vulnerabilities-cbc-mode

**Comment by MarcoRossignoli** [comment]
Ah...also some "unit testing" could be a good addition. You could take a cue from this repo organization https://github.com/tonerdo/coverlet

**Comment by MarcoRossignoli** [comment]
> I am also thinking to add other encryption algorithms or encoding decoding flags.

IMHO for now since the project is very young you could re-organize repo with better structure src/test/docs folder, you could add a "build.cmd" command to allow to contributor to clone/build(and run test) in a simple way.
After that you could add a contributor guide...in this way it's simple for other developers propose PRs.
You could add automatic build with Azure Pipeline(free for OSS) https://azure.microsoft.com/en-us/pricing/details/devops/azure-pipelines/
If you want to have a little chat DM me on twitter, I could bring my experience as contributor.

**Comment by tomchavakis** [comment]
@MarcoRossignoli  thank you so much for your help and the guidelines.

**Comment by tomchavakis** [comment]
Hi Marco,

New Version 1.0.5 with Usage and Secure Password added to the nuget.
