### ISSUE TITLE
Enable passing the password as a command line argument.

### ISSUE THREAD

**Issue by voroninp** [tomchavakis/encrypto#7]
This SO [question](https://stackoverflow.com/questions/55138580/what-are-the-options-for-deploying-files-with-sensitive-data) explains the motivation, why having this feature would be nice.

**Comment by tomchavakis** [comment]
Hi @voroninp , 

I would like to thank you for your contribution. 
I will start the development of this feature asap and I will inform you when it's ready.

**Comment by voroninp** [comment]
@tomchavakis  Can I help somehow?

**Comment by tomchavakis** [comment]
Can you describe the requirements of this feature ?
- Password as command line parameter
 - what else ??

If you will use the 
 dotnet-encrypto encrypt -t "tom"
the result is base64 

Feel free to join the project.
Thanks @voroninp

**Comment by voroninp** [comment]
Ideally I would like to use it in a way how [ansible-vault](https://docs.ansible.com/ansible/latest/user_guide/playbooks_vault.html) works.

For example:
I have a text file, I  want to encrypt it, encode as base64 and put it in source control.
And then I need the reverse procedure when deploying.

I also think that we should have an option to provide the output file name. This can help avoid accidental commits of unencrypted sensitive data.

How I see it:

I put in `.gitignore`  the pattern `sensitive.*`. Then I create file  `sensitive.credentials.json` and call: 

`dotnet encrypto encrypt -i  sensitive.credentials.json -o credentials.json --base64 --decrypt-to-source`

`-o` - specifies the name of the file with encrypted data.
`--base64` - asks to encode contents in base64
`--decrypt-to-source` - asks encrypto do decrypt the contents later to the file with the name used as the source for encryption, that is `sensitive.credentials.json`. This last feature would be very helpful because it leaves little chance of forgetting the prefix `sensitive.` for the `decrypt` output name. But it implies that encrypted file should be in particular format to store this setting. It's "expensive" feature, I suppose. So it would be fine just to be able to call:

`dotnet encrypto encrypt -i  sensitive.credentials.json -o credentials.json --base64`
and
`dotnet encrypto decrypt -i  credentials.json -o sensitive.credentials.json --base64`

**Comment by tomchavakis** [comment]
@voroninp  thanks for the detailed explanation, this feature is really great and useful.

**Comment by tomchavakis** [comment]
@voroninp I am thinking about the security of the ability to pass the password as command line parameter.
Later if someone has access to the machine that the encryption occurred, with history command the password will be unencrypted.
What do you think? 
What if the password will be stored at a password json/txt file?

**Comment by voroninp** [comment]
Good point, yet I am not sure whether history is saved if action is done automatically outside terminal.

My intention was to run decryption on each target machine as a deployment step of Octopus release process. So I could pass the variable for the password.

`dotnet encrypto decrypt -i file -p #{Password}`

If `#{Password}` variable has type `sensitive` it is not logged, though I am not sure about command line as a whole:)
Anyway, target machine will contain unencrypted data :) So if anyone has access to the machine, he already has sensitive data.

**Comment by tomchavakis** [comment]
Hi @voroninp 

This feature added.
Please verify that the functionality is fine.

**Comment by tomchavakis** [comment]
You can use also the dotnet tool at version 1.0.6

https://www.nuget.org/packages/dotnet-encrypto

**Comment by voroninp** [comment]
Great. Thanks for the speed! 

But without base64 encoding Git is a bit upset with all these bytes. And output option would be much appreciated.

**Comment by tomchavakis** [comment]
@voroninp  Base64 supported if you add -t as parameter for text encryption.
I would add this functionality also for files.

**Comment by tomchavakis** [comment]
@voroninp base64 file encoding supported at the latest version

**Comment by tomchavakis** [comment]
https://www.nuget.org/packages/dotnet-encrypto/1.0.7

**Comment by voroninp** [comment]
Any plans for `-o` - output option? ;-)

**Comment by tomchavakis** [comment]
Hi @voroninp -o supported by --base64 option parameter

ex.
`dotnet-encrypto encrypt -i /home/tcs/Downloads/file.txt --base64 -p "123"`

**Comment by voroninp** [comment]
@tomchavakis May be I missed it in code, but I do not see any option where I can specify the name of the encrypted file. I mean that currently the contents of the source file is encrypted/replaced.

**Comment by tomchavakis** [comment]
ok You mean that you want the encrypted output to stored at a specific file.
I will add it asap.

**Comment by tomchavakis** [comment]
Hi @voroninp .

The output feature exists at the version 1.0.8

https://www.nuget.org/packages/dotnet-encrypto/1.0.8

**Comment by voroninp** [comment]
@tomchavakis  Man you are a hero =)

**Comment by tomchavakis** [comment]
thanx @voroninp

**Comment by voroninp** [comment]
And one more question. This is not even close to critical. It is only about convenience/safety, though it looks to be the most expensive feature in terms of effort.

Would be nice to save somehow the original file name in the encrypted file, and use it automatically for decryption. I explained the motivation above, but I'll repeat.

This lets me to add pattern `unencrypted.*` to `.gitignore` file, and avoid unintentional commit of sensitive unencrypted data.

`dotnet encrypto encrypt -i unencrypted.data.json --base64 -p password -o encrypted.data`

So the outcome is `encrypted.data` file which "remembers" the name of initial file.

Later someone checks out the branch and calls:

`dotnet encrypto decrypt -i encrypted.data --base64 -p password`

He neither has to specify filename, nor even know the convention about `unencrypted.*`.
So he ends up with two files in folder: `unencrypted.data.json` and `encrypted.data`. The first one is ignored, and after it is edited one must call again `dotnet encrypto encrypt -i unencrypted.data.json --base64 -p password -o encrypted.data` what leads to changes in `encrypted.data` file which is tracked and could be safely committed.

**Comment by tomchavakis** [comment]
Hi @voroninp,

This feature is awesome and really useful. 
I will try to implement it asap. 
The best way, would be to pass as metadata to the file in some way, and not depict the. actual data. 
Thanks again for these nice features.

**Comment by voroninp** [comment]
But then there are disputable things, actually.

If there is a metadata, should `encrypto` even allow `-o` option for decryption?
If not, should it warn about already existing unencrypted file and ask about permission to overwrite it? Should `-f/--force-overwrite` option exist for automation tools?

**Comment by tomchavakis** [comment]
i think that your point is right. 
Metadata also doesn't works the same in all OS, so it would be better to append to the encrypted file.

**Comment by voroninp** [comment]
Even when it is not in metadata but in file.

 I mean what should `encrypto` do, if you specify `-o file` and this `file` already exists. The same about “saved” filename.

All these corner cases :’(

**Comment by voroninp** [comment]
I have an idea. We can just store this info in another committed file. Like encrypto.settings ;)

**Comment by tomchavakis** [comment]
Hi @voroninp ,

I agree with you, this would be fine.

**Comment by tomchavakis** [comment]
Hi @voroninp 

I use the Environment.SpecialFolder.ApplicationData in Windows and Environment.SpecialFolder.UserProfile in Linux and OSX in order to store the encrypto.settings file.
This file stores the original and encrypted mapping filename in a JSON format.
So if you are going to delete the original file then the decryption process will restore the file at the original location.

You can use the version 1.1.0 

`dotnet tool install --global dotnet-encrypto --version 1.1.0`

If you find any bugs or anything inappropriate just inform me to fix the issues.

Thanks again

**Comment by voroninp** [comment]
Thanks a lot. Is local settings file supported as well?

Otherwise settings file won’t be committed and hence checked out. It means the mapping won’t exist on a fresh system, which just hired developer is very likely to have.

**Comment by tomchavakis** [comment]
Hi @voroninp ,

You will find a new command-line parameter --local-output.
ex.
`dotnet dotnet-encrypto.dll encrypt -i ~/Downloads/logs/original.log -o ~/Downloads/logs/encrypted.log -p "123" --base64 --local-output`

This command creates encrypto.settings file to the directory of the original file.

Use version 1.1.1

https://www.nuget.org/packages/dotnet-encrypto/1.1.1

**Comment by voroninp** [comment]
```
dotnet encrypto encrypt -i data.txt --base64 -o data.encrypted --local-output -p vpv
```
then
```
dotnet encrypto decrypt -i data.encrypted  --base64 -p vpv
```
Getting `data.encrypted | Result:Decryption failed`.
Works for text from this file, though.

**Comment by tomchavakis** [comment]
Hi @voroninp 
What is your operating system?

**Comment by voroninp** [comment]
Mac OS

**Comment by tomchavakis** [comment]
Thanks, @voroninp,

I will check it

**Comment by voroninp** [comment]
Yep, checked in Windows - it works.

**Comment by tomchavakis** [comment]
I found the bug, I will upload the new version asap

**Comment by tomchavakis** [comment]
Hi @voroninp 

Can you test this version on Mac? 

https://www.nuget.org/packages/dotnet-encrypto/1.1.2

**Comment by voroninp** [comment]
Now it works.

Btw, I noticed that in case of invalid characters when base64 encoding is expected, tool fails with not that user friendly message ;-)

> dotnet encrypto decrypt -t $%$#%34 -p vpv
>
> Unhandled Exception: System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at Encrypto.Utils.Utilities.Base64Decode(String plainText) in /home/tom/Projects/github/encrypto/src/Encrypto.Utils/Utilities.cs:line 17
   at Encrypto.Helpers.DecryptText() in /home/tom/Projects/github/encrypto/src/Encrypto/Helpers/ConsoleHelpers.cs:line 116
   at Encrypto.Program.<>c.<Main>b__0_1(DecryptOptions options) in /home/tom/Projects/github/encrypto/src/Encrypto/Program.cs:line 56
   at Encrypto.Program.Main(String[] args) in /home/tom/Projects/github/encrypto/src/Encrypto/Program.cs:line 15

**Comment by tomchavakis** [comment]
This bug fixed at the latest version 1.1.4

https://www.nuget.org/packages/dotnet-encrypto

**Comment by tomchavakis** [comment]
Hi @voroninp 

May I close this issue ?

**Comment by voroninp** [comment]
@tomchavakis I believe, yes. Thanks.
